export type Toc = Library[];

interface Library {
  contents: Content[];
  order: number;
  enComplete: boolean;
  heComplete: boolean;
  enDesc: string;
  heDesc: string;
  enShortDesc: string;
  heShortDesc: string;
  heCategory: string;
  category: Category;
}

interface ContainerContent {
  contents: Content[];
  order?: number;
  enComplete?: boolean;
  heComplete?: boolean;
  enDesc?: string;
  heDesc?: string;
  enShortDesc: string;
  heShortDesc: string;
  heCategory?: string;
  category: string;
  searchRoot?: string;
  isPrimary?: boolean;
}

interface CategoryContent {
  categories: string[];
  dependence?: Dependence;
  collectiveTitle?: CollectiveTitle;
  heCollectiveTitle?: HeCollectiveTitle;
  commentator?: CollectiveTitle;
  heCommentator?: HeCollectiveTitle;
  base_text_order?: number;
  hidden?: boolean;
  order?: number;
  primary_category: Category;
  enShortDesc: string;
  heShortDesc: string;
  corpus?: Category;
  title: string;
  heTitle: string;
}

interface CollectionContent {
  categories: string[];
  name: string;
  slug: string;
  isCollection: true;
  enComplete: boolean;
  heComplete: boolean;
  enShortDesc: string;
  heShortDesc: string;
  title: string;
  heTitle: string;
  nodeType: 'TocCollectionNode';
}

export type Content = CategoryContent | CollectionContent | ContainerContent;

type Category =
  | 'Bavli'
  | 'Tanakh'
  | 'Commentary'
  | 'Mishnah'
  | 'Targum'
  | 'Yerushalmi'
  | 'Midrash Rabbah'
  | 'Guides'
  | 'Midrash'
  | 'Halakhah'
  | 'Kabbalah'
  | 'Liturgy'
  | 'Jewish Thought'
  | 'Chasidut'
  | 'Musar'
  | 'Responsa'
  | 'Second Temple'
  | 'Reference'
  | 'Talmud'
  | 'Tosefta';

type Dependence = 'Targum' | 'Commentary' | 'Guides' | 'Midrash';

type CollectiveTitle =
  | 'Abarbanel'
  | 'Abraham Cohen'
  | 'Alon Bakhut'
  | 'Alshich'
  | 'Amudei Yerushalayim'
  | 'Annotations of Maharatz Chajes'
  | 'Annotations of Minchat Chinukh'
  | 'Aramaic Targum'
  | 'Ateret Zekenim'
  | 'Avi Ezer'
  | 'Avigdor Shinan'
  | 'Avodat HaMelekh'
  | 'Baal HaMaor'
  | 'Bartenura'
  | 'Batei HaNefesh'
  | 'Bavli'
  | 'Bedek HaBayit'
  | 'Bein HaShitin'
  | 'Beit Meir'
  | 'Beit Shmuel'
  | 'Bekhor Shor'
  | 'Ben Aryeh'
  | 'Ben Yehoyada'
  | 'Benayahu'
  | 'Benei Ahuvah'
  | 'Benei Binyamin'
  | 'Beur HaGra'
  | 'Beur Reuven'
  | 'Binah LeIttim'
  | 'Binyan Yehoshua'
  | 'Birkat Avraham'
  | 'Boaz'
  | 'Brief Commentary'
  | 'Brit Olam'
  | 'Buber footnotes'
  | 'Cassuto'
  | 'Chafetz Chaim'
  | 'Chatam Sofer'
  | 'Chelkat Mechokek'
  | 'Chemdat Yisrael'
  | 'Cheshek Shlomo'
  | 'Chiddushei Anshei Shem'
  | 'Chiddushei HaRambam'
  | 'Chiddushei Hilkhot Niddah'
  | 'Chiddushei Rabbi Akiva Eiger'
  | 'Chiddushei Ridbaz'
  | 'Chidushei Agadot'
  | 'Chidushei Chatam Sofer'
  | 'Chidushei Halachot'
  | 'Chidushei HaRadal'
  | 'Chidushei Mayim Chayim'
  | 'Chidushei Rabbi Eliyahu of Greiditz'
  | 'Chidushim of Machaneh Ephraim'
  | 'Chizkuni'
  | 'Chok Yaakov'
  | 'Chokhmat Shlomo'
  | 'Chomat Anakh'
  | 'Comment'
  | 'Commentary of Chida'
  | 'Commentary of Mahari Kurkus and Radbaz'
  | 'Commentary of the Rosh'
  | 'Commentary on Sefer Hamitzvot of Rasag'
  | 'Commentary'
  | 'Crescas'
  | 'Daat Zkenim'
  | 'Daf Shevui'
  | 'Dagul MeRevava'
  | 'Divrei Negidim'
  | 'Divrei Shaul Edut BeYosef'
  | 'Divrei Yirmiyahu'
  | 'Divrey Chamudot'
  | 'Efodi'
  | 'Ein Yosef'
  | 'Eliyah Rabbah'
  | 'Eliyahu Rabbah'
  | 'Em LaMikra'
  | 'English Explanation of Mishnah'
  | 'Ephod Bad'
  | 'Eshel Avraham'
  | 'Etz Yosef'
  | 'Everett Fox'
  | 'Ezer MiKodesh'
  | 'Ezra ben Solomon'
  | 'Footnotes'
  | 'German Commentary'
  | 'Geulat Olam'
  | 'Gilyon HaShas'
  | 'Gra'
  | 'Gur Aryeh'
  | 'Haamek Davar'
  | 'Haamek Sheilah'
  | 'Hadar Zekenim'
  | 'Hagahot Chavot Yair'
  | 'Hagahot HaBach'
  | 'Hagahot Imrei Barukh'
  | 'Hagahot MeAlfas Yashan'
  | 'Haggahot and Marei Mekomot'
  | 'Haggahot Chadashot on Sefer Mitzvot Katan'
  | 'Haggahot Kevod Melakhim'
  | 'Haggahot Rabbeinu Peretz on Sefer Mitzvot Katan'
  | 'Haggahot Rabbi Menachem di Lonzano'
  | 'Haggahot RaDO'
  | 'Haggahot YaFeM'
  | 'Haggahot'
  | 'HaKtav VeHaKabalah'
  | 'HaMaor'
  | 'Har HaMoriyah'
  | 'Harchev Davar'
  | 'Hasagot HaRamban'
  | 'Hon Ashir'
  | 'Ibn Ezra'
  | 'Iggeret Shmuel'
  | 'Ikar Tosafot Yom Tov'
  | 'Imrei Yosher'
  | 'Ish Kilvavo;'
  | 'Joseph ibn Yahya'
  | 'JPS'
  | 'Kaf HaChayim'
  | 'Katuv Sham'
  | 'Kereti'
  | 'Kessef HaKodashim'
  | 'Kessef Mishneh'
  | 'Ketem Paz'
  | 'Ketzot HaChoshen'
  | 'Kikar LaAden'
  | 'Kimcha Davshuna'
  | 'Kinaat Sofrim'
  | 'Kiryat Sefer'
  | 'Kisse Rahamim'
  | 'Kli Yakar'
  | 'Kol Yaakov'
  | 'Korban HaEdah'
  | 'Korban Netanel'
  | 'Kos Shel Eliyahu'
  | 'Kovetz Al Yad HaChazakah'
  | 'Ktav Yad Rashi'
  | 'Kuntres Acharon'
  | 'Lechem Mishneh'
  | 'Lechem Shamayim'
  | 'Lev Hakhamim'
  | 'Lev Sameach'
  | 'Lev Shalem'
  | 'Levushei Serad'
  | 'Maadaney Yom Tov'
  | 'Maarechet Heidenheim'
  | 'Maaseh Nissim'
  | 'Maaseh Rokeach'
  | 'Machatzit HaShekel'
  | 'Magen Avot'
  | 'Magen Avraham'
  | 'Maggid Mishneh'
  | 'Maharam of Padua'
  | 'Maharam Schiff'
  | 'Maharam'
  | 'Maharzu Hakatzar'
  | 'Malbim Beur Hamilot'
  | 'Malbim'
  | 'Marbeh Lesaper'
  | 'Mareh HaPanim'
  | 'Marganita Tava'
  | 'Marit HaAyin'
  | 'Maskil LeDavid'
  | 'Masoret HaTosefta'
  | 'Mateh Yehonatan'
  | 'Matnot Kehunah'
  | 'MeAvur HaAretz;'
  | 'Mechir Yayin'
  | 'Mefaresh'
  | 'Megilat Esther'
  | 'Megillat Setarim'
  | 'Meir Ayin'
  | 'Meiri'
  | 'Mekor Mayim Chayim'
  | 'Mekorei HaRambam LeRashash'
  | 'Melekhet Shelomoh'
  | 'Menot HaLevi'
  | 'Meshech Hochma'
  | 'Mesorat HaShas'
  | 'Metzudat David'
  | 'Metzudat Zion'
  | 'Midrash Lekach Tov'
  | 'Migdal Oz'
  | 'Mikdash Melekh, RaMaZ Commentary'
  | 'Mikdash Melekh'
  | 'Milchemet Hashem'
  | 'Minchat Ani'
  | 'Minchat Shai'
  | 'Minei Targuma'
  | 'Mishmeret HaBayit'
  | 'Mishnat DeRabbi Eliezer'
  | 'Mishnat Eretz Yisrael'
  | 'Mishneh LaMelech'
  | 'Mitzpeh Etan'
  | 'Mizrachi'
  | 'Nachal Eitan'
  | 'Nachal Eshkol'
  | 'Nachal Kedumim'
  | 'Nachalat Avot'
  | 'Naftali Seva Ratzon'
  | 'Nahalat Yaakov'
  | 'Narboni'
  | 'Nefesh David'
  | 'Nekudot HaKesef'
  | 'Netiv Chayim'
  | 'Netiv Chesed'
  | 'Netivot HaMishpat, Beurim'
  | 'Netivot HaMishpat, Hidushim'
  | 'New Nuschah'
  | 'Nimukei Yosef'
  | 'Notes and Corrections on Midrash Aggadah'
  | 'Notes and Corrections'
  | 'Notes by Heinrich Guggenheimer'
  | 'Notes by Rabbi Yehoshua Hartman'
  | 'Nuschaot from Manuscripts'
  | 'Nuschaot Ktav Yad'
  | 'Ohr HaChamah'
  | 'Ohr LaYesharim'
  | 'Ohr Penimi'
  | 'Ohr Sameach'
  | 'Onkelos'
  | 'Or HaChaim'
  | 'Palgei Mayim'
  | 'Pat Lechem'
  | 'Peh Echad'
  | 'Peleti'
  | 'Penei David'
  | 'Penei Moshe'
  | 'Penei Yehoshua'
  | 'Peninei Halakhah'
  | 'Peri Chadash'
  | 'Perush Kadmon'
  | 'Perush Maharzu'
  | 'Petach Einayim'
  | 'Pilpula Charifta'
  | 'Pirkei Moshe'
  | 'Piskei Tosafot'
  | 'Pitchei Teshuva'
  | 'Pri Megadim'
  | 'Pri Yitzhak'
  | 'Rabbeinu Bahya'
  | 'Rabbeinu Chananel'
  | 'Rabbeinu Efrayim'
  | 'Rabbeinu Gershom'
  | 'Rabbeinu Yehonatan of Lunel'
  | 'Rabbeinu Yonah'
  | 'Rabbi Akiva Eiger'
  | 'Radak'
  | 'Ralbag Beur HaMilot'
  | 'Ralbag'
  | 'Rambam'
  | 'Ramban'
  | 'Ran'
  | 'Rash MiShantz'
  | 'Rashash'
  | 'Rashba (Attributed)'
  | 'Rashba'
  | 'Rashbam'
  | 'Rashi'
  | 'Rav Hirsch'
  | 'Rav Nissim Gaon'
  | 'Reggio'
  | 'Reshimot Shiurim'
  | 'Rif'
  | 'Rishon Letzion'
  | 'Rishonim on Talmud'
  | 'Ritva'
  | 'Riva'
  | 'Rosh'
  | 'Saadia Gaon'
  | 'Safa Echat'
  | 'Second Version of Ibn Ezra'
  | 'Seder Mishnah'
  | 'Sefer HaMenucha'
  | 'Sefer HaZekhut'
  | 'Sela HaMachlakot'
  | 'Sforno'
  | 'Shadal'
  | 'Sheilat Shalom'
  | 'Shem Tov'
  | 'Sheyarei Korban'
  | 'Shibolei HaLeket'
  | 'Shiltei HaGiborim'
  | 'Shita Mekubetzet'
  | 'Shorshei HaYam'
  | 'Siftei Chakhamim'
  | 'Siftei Kohen'
  | 'Simchat HaRegel'
  | 'Sources and References'
  | 'Steinsaltz'
  | 'Sulam'
  | 'Summary of Shakh'
  | 'Summary of Taz'
  | 'Tafsir Rasag'
  | 'Talmud'
  | 'Targum Jerusalem'
  | 'Targum Jonathan'
  | 'Targum Neofiti'
  | 'Targum Sheni'
  | 'Teshuvah MeYirah'
  | 'Tiferet Shmuel'
  | 'Tiferet Yisrael'
  | 'Toledot Yitzchak'
  | 'Torah Temimah'
  | 'Torat HaShlamim'
  | 'Tosafot Chad Mikamei'
  | 'Tosafot HaRid'
  | 'Tosafot HaRosh'
  | 'Tosafot Rabbi Akiva Eiger'
  | 'Tosafot Ri HaZaken'
  | 'Tosafot Rid'
  | 'Tosafot Shantz'
  | 'Tosafot Yeshanim'
  | 'Tosafot Yom Tov'
  | 'Tosafot'
  | 'Tosefta (Lieberman)'
  | 'Tosefta Kifshutah'
  | 'Tov haLevanon'
  | 'Tumat Yesharim'
  | 'Tur HaAroch'
  | 'Turei Zahav'
  | 'Tziunei Maharan'
  | 'Tzror HaMor'
  | 'Urim VeTumim, Tumim'
  | 'Urim VeTumim, Urim'
  | 'Variants'
  | 'Yaakov Emden'
  | 'Yachin'
  | 'Yad Avraham'
  | 'Yad David'
  | 'Yad Eitan'
  | 'Yad Ephraim'
  | 'Yad Ramah'
  | 'Yedei Moshe'
  | 'Yefeh Anaf'
  | 'Yefeh Kol'
  | 'Yein Levanon'
  | 'Yekar Tiferet'
  | 'Yeriot Shlomo'
  | 'Yesh Seder LaMishnah'
  | 'Yesha Elohim'
  | 'Yismach Yisrael'
  | 'Yitzchak Yeranen'
  | 'Zeroa Yamin'
  | 'Zevach Pesach'
  | "Ali Be'er"
  | "Annotations of R' Yeshaya Berlin"
  | "Annotations of R' Zalman of Vilna"
  | "Ba'al HaTurim"
  | "Ba'er Hetev"
  | "Be'er HaGolah"
  | "Be'er Mayim Chaim"
  | "Beur HaRe'em"
  | "Even Ha'azel"
  | "Gra's Nuschah"
  | "Ha'atakat Teshuvat HaRif"
  | "Hafla'ah ShebaArakhin"
  | "Haggahot of R' David Luria on Sefer HaParnas"
  | "Haggahot R' Yeshaya Berlin"
  | "Haggahot Ya'avetz"
  | "Hasagot HaRa'avad"
  | "Kitzur Ba'al HaTurim"
  | "Lechem Dim'ah"
  | "Ma'asai LaMelekh"
  | "Marpeh la'Nefesh"
  | "Me'irat Einayim"
  | "Peirush Hafla'ah"
  | "Publisher's Haggahot on Sefer HaParnas"
  | "Ra'ah"
  | "Ra'avad"
  | "Sha'ar HaMelekh"
  | "Sha'arei Teshuvah"
  | "Ta'alumot Chokhmah"
  | "Toafot Re'em"
  | "Tzafnat Pa'neach"
  | "Yefeh To'ar"
  | "Yekhahen Pe'er";

type HeCollectiveTitle =
  | ' הגהות הרד"ל על ספר הפרנס'
  | 'אבי עזר'
  | 'אביגדור שנאן'
  | 'אבן האזל'
  | 'אבן עזרא מהדורא תניינא'
  | 'אבן עזרא'
  | 'אברבנאל'
  | 'אברהם כהן'
  | 'אברט פוקס'
  | 'אגרת שמואל'
  | 'אור החיים'
  | 'אור החמה'
  | 'אור לישרים'
  | 'אור פנימי'
  | 'אור שמח'
  | 'אורים ותומים, אורים'
  | 'אורים ותומים, תומים'
  | 'איש כלבבו;'
  | 'אלון בכות'
  | 'אליה רבה'
  | 'אליהו רבא'
  | 'אלשיך'
  | 'אם למקרא'
  | 'אמרי יושר'
  | 'אפוד בד'
  | 'אפודי'
  | 'אשל אברהם'
  | 'באור הרא"ם'
  | 'באורי מהר"י קורקוס והרדב"ז'
  | 'באר הגולה'
  | 'באר היטב'
  | 'באר מים חיים'
  | 'בדק הבית'
  | 'בועז'
  | 'ביאור אנגלי על המשנה'
  | 'ביאור הגר"א'
  | 'ביאור יש"ר'
  | 'ביאור על ספר המצוות לרס"ג'
  | 'ביאור ראובן'
  | 'ביאור שטיינזלץ'
  | 'בין השיטין'
  | 'בינה לעתים'
  | 'בית מאיר'
  | 'בית שמואל'
  | 'בכור שור'
  | 'בן אריה'
  | 'בן יהוידע'
  | 'בני אהובה'
  | 'בני בנימין'
  | 'בניהו'
  | 'בנין יהושע'
  | 'בעל הטורים '
  | 'ברטנורא'
  | 'ברית עולם'
  | 'ברכת אברהם'
  | 'בתי הנפש'
  | 'גאולת עולם'
  | 'גור אריה'
  | 'גליון הש"ס'
  | 'גר"א'
  | 'דברי חמודות'
  | 'דברי ירמיהו'
  | 'דברי נגידים'
  | 'דברי שאול - עדות ביוסף'
  | 'דגול מרבבה'
  | 'דעת זקנים'
  | 'דף שבועי'
  | 'הגהות אמרי ברוך'
  | 'הגהות הב"ח'
  | 'הגהות הגרי״ב'
  | 'הגהות המו"ל על ספר הפרנס'
  | 'הגהות הרד"ל על ספר הפרנס'
  | 'הגהות ומראה מקומות'
  | 'הגהות חדשות על ספר מצוות קטן'
  | 'הגהות חוות יאיר'
  | 'הגהות יעב"ץ'
  | 'הגהות יפ"מ'
  | 'הגהות כבוד מלכים'
  | 'הגהות מאלפס ישן'
  | 'הגהות מהר"ם די לונזאנו'
  | 'הגהות מהר"ם פדווא'
  | 'הגהות רבי עקיבא איגר'
  | 'הגהות רבנו פרץ על ספר מצוות קטן'
  | 'הגהות רד"א'
  | 'הגהות'
  | 'הדר זקנים'
  | 'הון עשיר'
  | 'הטור הארוך'
  | 'הכתב והקבלה'
  | 'המאור'
  | 'הסולם'
  | 'העמק דבר'
  | 'העמק שאלה'
  | 'הערות בובר'
  | 'הערות ותיקונים על מדרש אגדה'
  | 'הערות ותיקונים'
  | 'הערות מאת חיים גוגנהיימר'
  | 'הערות שוליים תרגום 1985 של JPS'
  | 'הערות שוליים'
  | 'העתקת פירוש הרי"ף'
  | 'הפלאה שבערכין'
  | 'הר המוריה'
  | 'הרחב דבר'
  | 'השגות הראב"ד'
  | 'השגות הרמב"ן'
  | 'זבח פסח'
  | 'זרוע ימין'
  | 'חדושי הלכות נדה'
  | 'חומת אנך'
  | 'חזקוני'
  | 'חידושי אגדות'
  | 'חידושי אנשי שם'
  | 'חידושי הלכות'
  | 'חידושי הרד״ל'
  | 'חידושי הרמב"ם'
  | 'חידושי חתם סופר'
  | 'חידושי מהר"א גריידץ'
  | 'חידושי מים חיים'
  | 'חידושי רבי עקיבא איגר'
  | 'חידושי רידב"ז'
  | 'חידושים והגהות הגרי"ב'
  | 'חידושים ומקורים מבעל מנחת חינוך'
  | 'חידושים ומקורים מהר"ץ חיות'
  | 'חידושים ומקורים מהרב זלמן מווילנא'
  | 'חידושים מהגאון בעל מחנה אפרים'
  | 'חכמת שלמה'
  | 'חלקת מחוקק'
  | 'חמדת ישראל'
  | 'חפץ חיים'
  | 'חק יעקב'
  | 'חשק שלמה'
  | 'חתם סופר'
  | 'טוב הלבנון'
  | 'טורי זהב'
  | 'יד אברהם'
  | 'יד איתן'
  | 'יד אפרים'
  | 'יד דוד'
  | 'יד רמה'
  | 'ידי משה'
  | 'יוסף אבן יחיא'
  | 'יין לבנון'
  | 'יכהן פאר'
  | 'יכין'
  | 'יעב"ץ'
  | 'יפה ענף'
  | 'יפה קול'
  | 'יפה תואר'
  | 'יצחק ירנן'
  | 'יקר תפארת'
  | 'יריעות שלמה'
  | 'יש סדר למשנה'
  | 'ישמח ישראל'
  | 'ישע אלהים'
  | 'כוס של אליהו'
  | 'ככר לאדן'
  | 'כלי יקר'
  | 'כסא רחמים'
  | 'כסף הקדשים'
  | 'כסף משנה'
  | 'כף החיים'
  | 'כרתי'
  | 'כתב יד רש"י'
  | 'כתוב שם'
  | 'כתם פז'
  | 'לב חכמים'
  | 'לב שלם'
  | 'לב שמח'
  | 'לבושי שרד'
  | 'לחם דמעה'
  | 'לחם משנה'
  | 'לחם שמים'
  | 'מאיר עין'
  | 'מאירי'
  | 'מאירת עיניים'
  | 'מגדל עוז'
  | 'מגיד משנה'
  | 'מגילת אסתר'
  | 'מגילת סתרים'
  | 'מגן אבות'
  | 'מגן אברהם'
  | 'מדרש לקח טוב'
  | 'מהר"ם שיף'
  | 'מהר"ם'
  | 'מהרז"ו הקצר'
  | 'מזרחי'
  | 'מחיר יין'
  | 'מחצית השקל'
  | 'מטה יהונתן'
  | 'מיני תרגומא'
  | 'מלאכת שלמה'
  | 'מלבי"ם באור המילות'
  | 'מלבי"ם'
  | 'מלחמת השם'
  | 'מנות הלוי'
  | 'מנחת עני'
  | 'מנחת שי'
  | 'מסורת הש״ס'
  | 'מסורת התוספתא'
  | 'מעבור הארץ;'
  | 'מעדני יום טוב'
  | 'מערכת היידענהיים'
  | 'מעשה ניסים'
  | 'מעשה רקח'
  | 'מעשי למלך'
  | 'מפרש'
  | 'מצודת דוד'
  | 'מצודת ציון'
  | 'מצפה איתן'
  | 'מקדש מלך, פירוש הרמ"ז'
  | 'מקדש מלך'
  | 'מקור מים חיים'
  | 'מקורי הרמב"ם לרש"ש'
  | 'מראה הפנים'
  | 'מראי מקומות הערות וציונים'
  | 'מראית העין'
  | 'מרבה לספר'
  | 'מרגניתא טבא'
  | 'מרפא לנפש'
  | 'משך חכמה'
  | 'משכיל לדוד'
  | 'משמרת הבית'
  | 'משנה למלך'
  | 'משנת ארץ ישראל'
  | 'משנת דרבי אליעזר'
  | 'מתנות כהונה'
  | 'נוסחא חדשה'
  | 'נוסחאות כ״י'
  | 'נוסחאות כתב יד'
  | 'נוסחת הגר״א'
  | 'נחל איתן'
  | 'נחל אשכול'
  | 'נחל קדומים'
  | 'נחלת אבות'
  | 'נחלת יעקב'
  | 'נימוקי יוסף'
  | 'נפש דוד'
  | 'נפתלי שבע רצון'
  | 'נקודות הכסף'
  | 'נרבוני'
  | 'נתיב חיים'
  | 'נתיב חסד'
  | 'נתיבות המשפט, ביאורים'
  | 'נתיבות המשפט, חידושים'
  | 'סדר משנה'
  | 'סלע המחלקות'
  | 'ספורנו'
  | 'ספר הזכות'
  | 'ספר המנוחה'
  | 'עבודת המלך'
  | 'עזר מקודש'
  | 'עזרא בן שלמה'
  | 'עטרת זקנים'
  | 'עין יוסף'
  | 'עיקר תוספות יום טוב'
  | 'עלי באר'
  | 'עמודי ירושלים'
  | 'עץ יוסף'
  | 'פה אחד'
  | 'פי׳ החיד״א'
  | 'פילפולא חריפתא'
  | 'פירוש גרמני'
  | 'פירוש הפלאה'
  | 'פירוש הרא"ש'
  | 'פירוש מהרז״ו'
  | 'פירוש קדמון'
  | 'פירוש קצר'
  | 'פירוש'
  | 'פירושים והערות מהרב יהושע הרטמן'
  | 'פלגי מים'
  | 'פלתי'
  | 'פני דוד'
  | 'פני יהושע'
  | 'פני משה'
  | 'פניני הלכה'
  | 'פסקי תוספות'
  | 'פרי חדש'
  | 'פרי יצחק'
  | 'פרי מגדים'
  | 'פרקי משה'
  | 'פת לחם'
  | 'פתח עינים'
  | 'פתחי תשובה'
  | 'ציוני מהר"ן'
  | 'צפנת פענח'
  | 'צרור המור'
  | 'קאסוטו'
  | 'קובץ על היד החזקה'
  | 'קול יעקב'
  | 'קונטרס אחרון'
  | 'קונטרס תשובה מיראה'
  | 'קיצור בעל הטורים '
  | 'קיצור ט"ז'
  | 'קיצור ש"ך'
  | 'קמחא דאבישונא'
  | 'קנאת סופרים'
  | 'קצות החושן'
  | 'קרבן העדה'
  | 'קרבן נתנאל'
  | 'קרית ספר'
  | 'קרשקש'
  | 'ר"ן'
  | 'ר"ש משאנץ'
  | 'רא"ה'
  | 'רא"ש'
  | 'ראב"ד'
  | 'ראשון לציון'
  | 'רב ניסים גאון'
  | 'רבינו אפרים'
  | 'רבינו גרשום'
  | 'רבינו חננאל'
  | 'רבינו יהונתן מלוניל'
  | 'רבינו יונה'
  | 'רבנו בחיי'
  | 'רד"ק'
  | 'רי"ף'
  | 'ריב"א'
  | 'ריטב"א'
  | 'רלב"ג ביאור המלות'
  | 'רלב"ג'
  | 'רמב"ם'
  | 'רמב"ן'
  | 'רש"י'
  | 'רש"ר הירש'
  | 'רש״ש'
  | 'רשב"א (מיוחס לו)'
  | 'רשב"א'
  | 'רשב"ם'
  | 'רשימות שיעורים'
  | 'שאילת שלום'
  | 'שבלי הלקט'
  | 'שד"ל'
  | 'שורשי הים'
  | 'שיטה מקובצת'
  | 'שיירי קרבן'
  | 'שינויי נוסחאות'
  | 'שלטי הגיבורים'
  | 'שם טוב'
  | 'שמחת הרגל'
  | 'שער המלך'
  | 'שערי תשובה'
  | 'שפה אחת'
  | 'שפתי חכמים'
  | 'שפתי כהן'
  | 'תולדות יצחק'
  | 'תומת ישרים'
  | 'תוספות הרא"ש'
  | 'תוספות הרי"ד'
  | 'תוספות חד מקמאי'
  | 'תוספות יום טוב'
  | 'תוספות ישנים '
  | 'תוספות ר"י הזקן'
  | 'תוספות רבי עקיבא איגר'
  | 'תוספות רי"ד'
  | 'תוספות שאנץ'
  | 'תוספות'
  | 'תוספתא (ליברמן)'
  | 'תוספתא כפשוטה'
  | 'תועפות ראם'
  | 'תורה תמימה'
  | 'תורת השלמים'
  | 'תעלומות חכמה'
  | 'תפארת ישראל'
  | 'תפארת שמואל'
  | 'תפסיר רס"ג'
  | 'תרגום אונקלוס'
  | 'תרגום יונתן'
  | 'תרגום ירושלמי'
  | 'תרגום ניאופיטי'
  | 'תרגום שני'
  | 'תרגום'
  | "ר' סעדיה גאון";
