export const letters = {
  א: '\u0294',
  ב: 'b',
  ג: '\u0261',
  ד: 'd',
  ה: 'h',
  '\u05d5': 'v',
  ז: 'z',
  ח: '\u03C7',
  '\u05d8': 't\u0320',
  '\u05d9': 'j',
  כ: '\u03C7',
  ך: '\u03C7',
  ל: 'l',
  מ: 'm',
  ם: 'm',
  נ: 'n',
  '\u05df': 'n',
  '\u05e1': 's',
  ע: '\u0294',
  פ: 'f',
  ף: 'f',
  צ: 't\u0320',
  ץ: 't\u0320',
  ק: 'k',
  ר: '\u0279',
  ש: '\u0283',
  ת: 's',
} as const;

export const namedLetters = {
  ALEPH: 'א',
  BAIS: 'ב',
  GIMMEL: 'ג',
  DALED: 'ד',
  HEY: 'ה',
  VAV: '\u05d5',
  ZAYIN: 'ז',
  CHES: 'ח',
  TES: '\u05d8',
  YUD: '\u05d9',
  CHOF: 'כ',
  CHOF_END: 'ך',
  LAMED: 'ל',
  MEM: 'מ',
  MEM_END: 'ם',
  NUN: 'נ',
  NUN_END: '\u05df',
  SAMECH: '\u05e1',
  EIYIN: 'ע',
  PEY: 'פ',
  PEY_END: 'ף',
  TZADDI: 'צ',
  TZADDI_END: 'ץ',
  KUF: 'ק',
  RAISH: 'ר',
  SHIN: 'ש',
  TOF: 'ת',
} as const;

export const dotted = {
  ב: 'v',
  כ: 'k',
  ך: 'k',
  פ: 'p',
  ף: 'p',
  ת: 't',
} as const;

export const punctuation = {
  '\u0591': 'ACCENT_ETNAHTA',
  '\u0592': 'ACCENT_SEGOL',
  '\u0593': 'ACCENT_SHALSHELET',
  '\u0594': 'ACCENT_ZAQEF_QATAN',
  '\u0595': 'ACCENT_ZAQEF_GADOL',
  '\u0596': 'ACCENT_TIPEHA',
  '\u0597': 'ACCENT_REVIA',
  '\u0598': 'ACCENT_ZARQA',
  '\u0599': 'ACCENT_PASHTA',
  '\u059A': 'ACCENT_YETIV',
  '\u059B': 'ACCENT_TEVIR',
  '\u059C': 'ACCENT_GERESH',
  '\u059D': 'ACCENT_GERESH_MUQDAM',
  '\u059E': 'ACCENT_GERSHAYIM',
  '\u059F': 'ACCENT_QARNEY_PARA',
  '\u05A0': 'ACCENT_TELISHA_GEDOLA',
  '\u05A1': 'ACCENT_PAZER',
  '\u05A3': 'ACCENT_MUNAH',
  '\u05A4': 'ACCENT_MAHAPAKH',
  '\u05A5': 'ACCENT_MERKHA',
  '\u05A6': 'ACCENT_MERKHA_KEFULA',
  '\u05A7': 'ACCENT_DARGA',
  '\u05A8': 'ACCENT_QADMA',
  '\u05A9': 'ACCENT_TELISHA_QETANA',
  '\u05AA': 'ACCENT_YERAH_BEN',
  '\u05AB': 'ACCENT_OLE',
  '\u05AC': 'ACCENT_ILUY',
  '\u05AD': 'ACCENT_DEHI',
  '\u05AE': 'ACCENT_ZINOR',
  '\u05AF': 'MARK_MASORA_CIRCLE',
  '\u05B0': 'POINT_SHEVA',
  '\u05B1': 'POINT_HATAF_SEGOL',
  '\u05B2': 'POINT_HATAF_PATAH',
  '\u05B3': 'POINT_HATAF_QAMATS',
  '\u05B4': 'POINT_HIRIQ',
  '\u05B5': 'POINT_TSERE',
  '\u05B6': 'POINT_SEGOL',
  '\u05B7': 'POINT_PATAH',
  '\u05B8': 'POINT_QAMATS',
  '\u05c7': 'POINT_QAMATS',
  '\u05ba': 'POINT_HOLAM',
  '\u05B9': 'POINT_HOLAM',
  '\u05BB': 'POINT_QUBUTS',
  '\u05BC': 'POINT_DAGESH',
  '\u05BD': 'POINT_METEG',
  '\u05BE': 'PUNCTUATION_MAQAF',
  '\u05BF': 'POINT_RAFE',
  '\u05C0': 'PUNCTUATION_PASEQ',
  '\u05C1': 'POINT_SHIN_DOT',
  '\u05C2': 'POINT_SIN_DOT',
  '\u05C3': 'PUNCTUATION_SOF_PASUQ',
  '\u05C4': 'MARK_UPPER_DOT',
  '\u05F3': 'PUNCTUATION_GERESH',
  '\u05F4': 'PUNCTUATION_GERSHAYIM',
} as const;

export const vowels = {
  POINT_HATAF_PATAH: '\u0251',
  POINT_PATAH: '\u0251',

  POINT_HATAF_SEGOL: '\u025B',
  POINT_SEGOL: '\u025B',

  POINT_QAMATS: '\u0264',
  POINT_HATAF_QAMATS: '\u0264',

  POINT_SHEVA: '\u0259\u032A',

  POINT_TSERE: '\u026A',

  POINT_HIRIQ: 'i',

  POINT_HOLAM: 'o',

  POINT_QUBUTS: 'u',
} as const;

export const Hashem = {
  segments: ['אֲ', 'דֹ', 'נָ', 'י֮'],
  graphemes: [
    {
      letter: 'א',
      POINT_HATAF_PATAH: true,
    },
    {
      letter: 'ד',
      POINT_HOLAM: true,
    },
    {
      letter: 'נ',
      POINT_QAMATS: true,
    },
    {
      letter: '\u05d9',
      ACCENT_ZINOR: true,
    },
  ],
  sounds: ['\u0294\u0251', 'do', 'nɤ', 'j'],
} as const;
